### ISSUE TITLE
just a suggestion

### ISSUE THREAD

**Issue by jayfreddy1994** [dalurness/server-time-bot#2]
hi team. bot is working as usual (21 may 2021).
my suggestion here if you want to improvise the bot:
1. adding calendar 
2. add server UTC for example [servertime 7:40PM at UTC+12]

those two are just my suggestion for now. it is all up to your decision to do it or not. thank you team.

**Comment by dalurness** [comment]
@jayfreddy1994 For the second one, I purposefully left off the timezone from the time as the point of the bot is to act as the  "server time", which is just the time within the server. Obviously this is reflecting some arbitrary timezone that you put in, but having the timezone displayed would infer that you should be able to have several time-zones displaying at once. From that point of view, it no longer fulfills its purpose anymore, as you're back to having to talk time-zones when trying to schedule things.

For your first suggestion, I'm not sure what you mean by adding a calendar. If what you mean by that is to be able to schedule events in the future and have that display in some channel somewhere... that sounds like a great idea! I'm not sure I have time to figure that out right now, but feel free to fork it and submit a pull request so we can all benefit from that added functionality.
